Repository wireapp/wire-ios-request-strategy, pull requests merged in 2021-11, with the labels that each got.

#369 [Feature] Self-deleting message config
  Cartfile
  Cartfile.resolved
  Sources/Payloads/Processing/PayloadProcessing+Conversation.swift
  Sources/Payloads/Processing/PayloadProcessing+ConversationTests.swift
  Sources/Request Strategies/Assets/AssetClientMessageRequestStrategyTests.swift
  Sources/Request Strategies/Assets/AssetV3DownloadRequestStrategyTests.swift
  Sources/Request Strategies/Assets/AssetV3PreviewDownloadRequestStrategyTests.swift
  Sources/Request Strategies/Assets/Helpers/LinkAttachmentsPreprocessorTests.swift
  Sources/Request Strategies/Assets/Helpers/LinkPreviewPreprocessor.swift
  Sources/Request Strategies/Assets/Helpers/LinkPreviewPreprocessorTests.swift
  Sources/Request Strategies/Assets/Link Preview/LinkPreviewAssetDownloadRequestStrategyTests.swift
  Sources/Request Strategies/Assets/Link Preview/LinkPreviewAssetUploadRequestStrategy.swift
  Sources/Request Strategies/Assets/Link Preview/LinkPreviewAssetUploadRequestStrategyTests.swift
  Sources/Request Strategies/Client Message/ClientMessageRequestFactoryTests.swift
  Sources/Request Strategies/Conversation/ConversationRequestStrategyTests.swift
  Sources/Request Strategies/Feature configurations/FeatureConfigRequestStrategy.swift
  Sources/Request Strategies/Feature configurations/FeatureConfigRequestStrategyTests.swift
Labels: API breaker

#416 chore: Integrate SwiftLint into the iOS-Request-Strategy Project IC-8
  .github/workflows/swiftlint.yml
  .swiftlint.yml
  WireRequestStrategy.xcodeproj/project.pbxproj
Labels: Fix PR Title 🤦‍♂️

#423 revert: Updating self-deleting messages SQSERVICES-1018
  Sources/Request Strategies/Feature configurations/FeatureConfigRequestStrategy.swift
  WireRequestStrategy.xcodeproj/xcshareddata/xcschemes/WireRequestStrategy.xcscheme
Labels: Patch

#424 revert: Self-deleting messages SQSERVICES-1018
  Cartfile
  Cartfile.resolved
  Sources/Payloads/Processing/PayloadProcessing+Conversation.swift
  Sources/Payloads/Processing/PayloadProcessing+ConversationTests.swift
  Sources/Request Strategies/Assets/AssetClientMessageRequestStrategyTests.swift
  Sources/Request Strategies/Assets/AssetV3DownloadRequestStrategyTests.swift
  Sources/Request Strategies/Assets/AssetV3PreviewDownloadRequestStrategyTests.swift
  Sources/Request Strategies/Assets/Helpers/LinkAttachmentsPreprocessorTests.swift
  Sources/Request Strategies/Assets/Helpers/LinkPreviewPreprocessor.swift
  Sources/Request Strategies/Assets/Helpers/LinkPreviewPreprocessorTests.swift
  Sources/Request Strategies/Assets/Link Preview/LinkPreviewAssetDownloadRequestStrategyTests.swift
  Sources/Request Strategies/Assets/Link Preview/LinkPreviewAssetUploadRequestStrategy.swift
  Sources/Request Strategies/Assets/Link Preview/LinkPreviewAssetUploadRequestStrategyTests.swift
  Sources/Request Strategies/Client Message/ClientMessageRequestFactoryTests.swift
  Sources/Request Strategies/Conversation/ConversationRequestStrategyTests.swift
  Sources/Request Strategies/Feature configurations/FeatureConfigRequestStrategy.swift
  Sources/Request Strategies/Feature configurations/FeatureConfigRequestStrategyTests.swift
  WireRequestStrategy.xcodeproj/xcshareddata/xcschemes/WireRequestStrategy.xcscheme
Labels: chore
