Repository wireapp/wire-ios-request-strategy, pull requests merged in 2021-06, with the labels that each got.

#307 [Feature] Support federation aware API for fetching prekeys
  Sources/Payloads/Payload+Processing.swift
  Sources/Payloads/Payload.swift
  Sources/Request Strategies/User Clients/FetchingClientRequestStrategyTests.swift
  Sources/Request Strategies/User Clients/MissingClientsMapTests.swift
  Sources/Request Strategies/User Clients/MissingClientsRequestFactory.swift
  Sources/Request Strategies/User Clients/MissingClientsRequestStrategy.swift
  Sources/Request Strategies/User Clients/MissingClientsRequestStrategyTests.swift
  Tests/Helpers/MessagingTestBase.swift
  WireRequestStrategy.xcodeproj/project.pbxproj
Labels: Minor changes

#308 [Feature] Support federation aware API for fetching user profiles
  Cartfile.resolved
  Sources/Helpers/Logging.swift
  Sources/Object Syncs/Helpers/IdentifierObjectSync.swift
  Sources/Payloads/Payload+Decoding.swift
  Sources/Payloads/Payload+Processing.swift
  Sources/Payloads/Payload.swift
  Sources/Payloads/PayloadTests+UserProfile.swift
  Sources/Protocols/SyncProgress.swift
  Sources/Request Strategies/User/UserProfileRequestStrategy.swift
  Sources/Request Strategies/User/UserProfileRequestStrategyTests.swift
  Tests/Helpers/MockObjects.swift
  WireRequestStrategy.xcodeproj/project.pbxproj
Labels: API breaker

#311 Rename data modal struct and enum for xcframework
  Cartfile
  Cartfile.resolved
  Sources/Helpers/EncryptionSessionDirectory+UpdateEvents.swift
  Sources/Helpers/ZMTBaseTests+CoreDataStack.swift
  Sources/Request Strategies/Assets/AssetV3UploadRequestStrategy.swift
  Sources/Request Strategies/Assets/Helpers/AssetsPreprocessor.swift
Labels: DO NOT MERGE
