Repository wireapp/wire-ios-request-strategy, pull requests merged in 2021-07, with the labels that each got.

#320 [Chore] Revert support for federation aware API for fetching prekeys
  Sources/Payloads/Payload+Processing.swift
  Sources/Payloads/Payload.swift
  Sources/Request Strategies/User Clients/FetchingClientRequestStrategyTests.swift
  Sources/Request Strategies/User Clients/MissingClientsMapTests.swift
  Sources/Request Strategies/User Clients/MissingClientsRequestFactory.swift
  Sources/Request Strategies/User Clients/MissingClientsRequestStrategy.swift
  Sources/Request Strategies/User Clients/MissingClientsRequestStrategyTests.swift
  Tests/Helpers/MessagingTestBase.swift
  WireRequestStrategy.xcodeproj/project.pbxproj
Labels: Minor changes

#322 Feature: xcframework
  Cartfile
  Cartfile.private
  Cartfile.resolved
  Resources/Configurations/WireRequestStrategy.xcconfig
  Resources/Configurations/zmc-config/ios-test-host.xcconfig
  Resources/Configurations/zmc-config/ios-test-target.xcconfig
  Resources/Configurations/zmc-config/ios.xcconfig
  Resources/Configurations/zmc-config/project-common.xcconfig
  WireRequestStrategy.xcodeproj/project.pbxproj
Labels: DO NOT MERGE

#330 [Feature] Add endpoint for fileSharing feature
  Sources/Request Strategies/Feature configurations/FeatureConfigRequestStrategy.swift
Labels: Feature request

#332 [Feature] Handling a new update event
  Cartfile.resolved
  Sources/Request Strategies/Feature configurations/FeatureConfigRequestStrategy.swift
  Sources/Request Strategies/Feature configurations/FeatureConfigRequestStrategyTests.swift
Labels: Feature request

#331 [Refactor] Feature configs
  Cartfile
  Cartfile.resolved
  Sources/Helpers/FeatureConfiguration/FeatureController.swift
  Sources/Request Strategies/Feature configurations/FeatureConfigRequestStrategy.swift
  Sources/Request Strategies/Feature configurations/FeatureConfigRequestStrategyTests.swift
  Tests/Helpers/FeatureControllerTest.swift
  WireRequestStrategy.xcodeproj/project.pbxproj
Labels: API breaker
