Repository wireapp/wire-ios-request-strategy, pull requests merged in 2022-02, with the labels that each got.

#481 feat: Separate access controls for guests ands services SQSERVICES-1052
  Cartfile.resolved
  Sources/Payloads/Payload+Conversation.swift
  Sources/Payloads/Processing/PayloadProcessing+Conversation.swift
  Sources/Payloads/Processing/PayloadProcessing+ConversationTests.swift
  Sources/Request Strategies/Conversation/ConversationRequestStrategyTests.swift
Labels: DO NOT MERGE

#482 feat: parse and handle classified domains feature config FS-96
  Cartfile.resolved
  Sources/Request Strategies/Feature configurations/FeatureConfigRequestStrategy.swift
Labels: API breaker

#485 fix: conversation not being fetched SQCALL-438
  Resources/Configurations/version.xcconfig
  Sources/Request Strategies/Conversation/ConversationRequestStrategy.swift
  Sources/Request Strategies/Conversation/ConversationRequestStrategyTests.swift
Labels: Patch
