Repository wireapp/wire-ios-request-strategy, pull requests merged in 2022-04, with the labels that each got.

#503 feat: classifications FS-95
  Cartfile
  Cartfile.resolved
  Resources/Configurations/version.xcconfig
  Sources/Request Strategies/Feature configurations/FeatureConfigRequestStrategy.swift
Labels: Minor changes

#509 fix: unable to remove a service from a conversation FS-637
  Resources/Configurations/version.xcconfig
  Sources/Request Strategies/Conversation/Actions/RemoveParticipantActionHandler.swift
  Sources/Request Strategies/Conversation/Actions/RemoveParticipantActionHandlerTests.swift
Labels: patch release

#511 fix: Badge icon doesn't show missed calls SQSERVICES-1111
  Resources/Configurations/version.xcconfig
  Sources/Notifications/Push Notifications/Notification Types/Content/ZMLocalNotification.swift
Labels: Patch
